---
- name: Install metric beat
  hosts: webservers
  become: true
  tasks:
    # Use command module
  - name: Download metricbeat
    command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.10.1-amd64.deb
    # Use command module
  - name: install metricbeat
    command: dpkg -i metricbeat-7.4.0-amd64.deb
    # Use copy module
  - name: drop in metricbeat config
    copy:
      src: /etc/ansible/metricbeat-config.yml
      dest: /etc/metricbeat/metricbeat.yml
    # Enable docker
  - name: enable and configure docker module for metric beat
    command: metricbeat modules enable docker
    # Setup software
  - name: setup metric beat
    command: metricbeat setup
    # Start up Metricbeat
  - name: start metric beat
    command: metricbeat -e



